name: Deploy on merge
on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    environment: dev
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
      - name: Check deployment status
        run: |
          flyctl status
          flyctl status --app cicd-demo
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

  deploy_prod:
    environment: prod
    needs: deploy_dev
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app cicd-demo-prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
      - name: Check deployment status
        run: |
          flyctl status
          flyctl status --app cicd-demo-prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
