name: Deploy on merge
on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    name: Deploy app
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Check deployment status
        run: |
          flyctl status
          flyctl status --app cicd-demo
