name: On Pull Request
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    


  preview:
    needs: test
    # Skip preview deployment if PR is closed
    if: github.event.action != 'closed'
    environment: dev
    name: Preview app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Create and deploy preview
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          flyctl apps create cicd-demo-pr-${{ github.event.pull_request.number }} || true
          flyctl deploy --remote-only --app cicd-demo-pr-${{ github.event.pull_request.number }}
          echo "Preview URL: https://cicd-demo-pr-${{ github.event.pull_request.number }}.fly.dev"

  cleanup:
    # Only run cleanup when PR is closed
    if: github.event.action == 'closed'
    environment: dev
    name: Cleanup preview
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Delete preview app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          flyctl apps destroy cicd-demo-pr-${{ github.event.pull_request.number }} -y || true