name: On Pull Request
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   environment: dev
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
    
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pytest fastapi httpx 

  preview:
    # needs: test
    environment: dev
    name: Preview app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy preview
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          flyctl deploy --remote-only --app cicd-demo-pr-${{ github.event.pull_request.number }}
          echo "Preview URL: https://cicd-demo-pr-${{ github.event.pull_request.number }}.fly.dev"